run_unpacker:
	$(MAKE) -C ./unpacker/ run

run_triton:
	$(MAKE) -C ./tritone/ run

run_tile16:
	$(MAKE) -C ./tile16/ run

run_text68:
	$(MAKE) -C ./text68/ run

run_simple:
	$(MAKE) -C ./simple/ run

run_screen:
	$(MAKE) -C ./screen/ run

run_play_ay:
	$(MAKE) -C ./play_ay/ run

run_demo:
	$(MAKE) -C ./demo/ run
